<?php
/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */

JFormHelper::loadFieldType('list');

class JFormFieldCities extends JFormFieldList
{
	protected function getOptions()
	{
		$options = parent::getOptions(); // TODO: Change the autogenerated stub

		$db = JFactory::getDbo();
		JHtmlBehavior::core();

		$doc = JFactory::getDocument();
		$doc->addScript('plugins/system/bliss/js/cities.js');
		$doc->addScriptDeclaration(<<<JS

JS
);

		$options[] = JHtmlSelect::option('123', 'Foo');

		return $options;
	}
}